commands:
  #HORA
  - commands:
    input : Que horas são?
    entity: time
    action: getTime
  - commands:
    input : Me diga a hora.
    entity: time
    action: getTime
  #DATA
  - commands:
    input : Qual é a data de hoje?
    entity: time
    action: getDate
  - commands:
    input : Data de hoje?
    entity: time
    action: getDate
  #Tempo
  - commands:
    input : Previsão do tempo
    entity: weather
    action: getWeather
  - commands:
    input : Como está o clima
    entity: weather
    action: getWeather
  #Abrir
  - commands:
    input : Abra o google
    entity: open
    action: 
  - commands:
    input : Abra o youtube
    entity: open
    action: 